version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - 5000:5000
    environment:
      - FRONTEND_PORT=5000
      - BACKEND_HOST=backend
      - BACKEND_PORT=8888
    depends_on:
      - backend
    restart: unless-stopped
  backend:
    build: ./backend
    ports:
      - 8888:8888
    environment:
      - BACKEND_PORT=8888
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: postgres:13.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    restart: unless-stopped